[package]
name = "vnt-jni"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vnt = {path="../vnt"}

jni = { version = "0.21.1", default-features = false }
[lib]
crate-type = ["staticlib", "cdylib"]